// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBa95FXekLunzj0Sy7sXz-X5_c-KSuBHBk',
    appId: '1:89415164093:web:a6b3289dd5e9c6b68317d4',
    messagingSenderId: '89415164093',
    projectId: 'events-testing-ef21e',
    authDomain: 'events-testing-ef21e.firebaseapp.com',
    storageBucket: 'events-testing-ef21e.firebasestorage.app',
    measurementId: 'G-FG1WYMVPPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOUMqVuuu-LTqi2S3s5bNF3DvNNFyvzus',
    appId: '1:89415164093:android:0603ac9db3ee2bf38317d4',
    messagingSenderId: '89415164093',
    projectId: 'events-testing-ef21e',
    storageBucket: 'events-testing-ef21e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq605vSlhaD6by1iBygAXP2dcVX0tHp3g',
    appId: '1:89415164093:ios:a29e793cb81ec3368317d4',
    messagingSenderId: '89415164093',
    projectId: 'events-testing-ef21e',
    storageBucket: 'events-testing-ef21e.firebasestorage.app',
    iosBundleId: 'com.example.nibbanaDhamma',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq605vSlhaD6by1iBygAXP2dcVX0tHp3g',
    appId: '1:89415164093:ios:a29e793cb81ec3368317d4',
    messagingSenderId: '89415164093',
    projectId: 'events-testing-ef21e',
    storageBucket: 'events-testing-ef21e.firebasestorage.app',
    iosBundleId: 'com.example.nibbanaDhamma',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBa95FXekLunzj0Sy7sXz-X5_c-KSuBHBk',
    appId: '1:89415164093:web:ddfe69a816325f168317d4',
    messagingSenderId: '89415164093',
    projectId: 'events-testing-ef21e',
    authDomain: 'events-testing-ef21e.firebaseapp.com',
    storageBucket: 'events-testing-ef21e.firebasestorage.app',
    measurementId: 'G-JJN511Z4LS',
  );
}
